data:
  num_classes: 345
  ignore_label: 700
  training_size: 345000

train:
  seed: 1588147245
  deterministic: False

dataset:
  name: transimgstrokedata
  root: /media/star/zjurobot/403/yangjingru/dataset/sequences
  num_points: 80000
  voxel_size: 1

num_epochs: 20 # 60 >80?
batch_size: 128

criterion:
  name: cross_entropy
  ignore_index: 700

optimizer:
  name: sgd
  lr: 0.03
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup

model:
  name: RNNnorm50

workers_per_gpu: 12
distributed: True
amp_enabled: False

